filebeat.inputs:
  - type: log
    enabled: true
    paths:
      - /applis/logs/demoELK/*.log
    multiline.type: pattern
    multiline.pattern: '^\[[0-9]{2}/[0-9]{2}/[0-9]{2}'
    multiline.negate: true
    multiline.match: after
    fields:
      category: api-messages

output.logstash:
  hosts: ["logstash-service.default:5044"]
