filebeat.inputs:
  - type: log
    enabled: true
    paths:
      - /applis/logs/demoELK/*.log
    multiline.type: pattern
    multiline.pattern: '^\[[0-9][0-9]/[0-9][0-9]/[0-9][0-9]'
    multiline.negate: true
    multiline.match: after
    processors:
      - timestamp:
          field: 'timestamp'  # Remplacez par le champ contenant la date dans votre log
          layouts: '02/01/06 15:04:05.000'  # Format de date attendu dans vos logs
    fields:
      category: api-messages

output.logstash:
  hosts: ["logstash-service.default:5044"]
