apiVersion: apps/v1
kind: Deployment
metadata:
  name: elasticsearch-deployment
spec:
  replicas: 1 # Définissez le nombre de répliques souhaitées
  selector:
    matchLabels:
      app: elasticsearch
  template:
    metadata:
      labels:
        app: elasticsearch
    spec:
      containers:
        - name: elasticsearch-container
          image: elastic-younes:1.0
          ports:
          - containerPort: 9200
            name: http
          - containerPort: 9300
            name: transport
---
apiVersion: v1
kind: Service
metadata:
  name: elasticsearch
spec:
  selector:
    app: elasticsearch  # Correspond au label utilisé dans le déploiement
  ports:
    - protocol: TCP
      port: 9200  # Port que vous souhaitez exposer
      targetPort: 9200  