apiVersion: apps/v1
kind: Deployment
metadata:
  name: filebeat
spec:
  replicas: 1
  selector:
    matchLabels:
      app: filebeats
  template:
    metadata:
      labels:
        app: filebeats
    spec:
      containers:
      - name: demo-elk
        image: demo-elk:2.1
        volumeMounts:
        - mountPath: /applis
          name: logs
      - name: filebeats
        image: filebeats-younes:2.1
        volumeMounts:
        - mountPath: /applis
          name: logs
      - name: metricbeats
        image: metricbeat-younes:1.0 
      volumes:
      - name: logs
        emptyDir: {}
