apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: manual
provisioner: k8s.io/manual
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: filebeats-pv-claim
  labels:
    app: filebeats
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Mi